config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :restaurants do
    resources :reviews, only: [:create]
  end
  # Defines the root path route ("/")
   root "restaurants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, :content, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: 0..5 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end


  def show
    @review = Review.new
  end


  def new
    @restaurant = Restaurant.new
  end


  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end


  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = @restaurant.reviews.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant), notice: 'Review was successfully created.'
    else
      render "restaurants/show", status: :unprocessable_entity
    end
  end


  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1 class="mt-4 mb-4">Edit Restaurant</h1>
  <%= form_with(model: @restaurant, local: true) do |form| %>
    <% if @restaurant.errors.any? %>
      <div class="alert alert-danger">
        <h4 class="alert-heading">Please fix the following errors:</h4>
        <ul>
          <% @restaurant.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :address, class: 'form-label' %>
      <%= form.text_field :address, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :category, class: 'form-label' %>
      <%= form.select :category, ['chinese', 'italian', 'japanese', 'french', 'belgian'], {}, class: 'form-select' %>
    </div>

    <%= form.submit 'Update Restaurant', class: 'btn btn-primary' %>
  <% end %>
  <%= link_to 'Back to List', restaurants_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <h1 class="mt-4 mb-4">Restaurants</h1>
  <div class="mb-3">
    <%= link_to 'New Restaurant', new_restaurant_path, class: 'btn btn-primary' %>
  </div>
  <div class="list-group">
    <% @restaurants.each do |restaurant| %>
      <div class="list-group-item">
        <h5 class="mb-1"><%= link_to restaurant.name, restaurant_path(restaurant) %></h5>
        <p class="mb-1"><%= restaurant.address %></p>
        <p class="mb-1"><%= restaurant.category.capitalize %></p>
        <%= link_to 'Edit', edit_restaurant_path(restaurant), class: 'btn btn-secondary btn-sm' %>
        <%= link_to 'Delete', restaurant_path(restaurant),  data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1 class="mt-4 mb-4">New Restaurant</h1>
  <%= form_with(model: @restaurant, local: true) do |form| %>
    <% if @restaurant.errors.any? %>
      <div class="alert alert-danger">
        <h4 class="alert-heading">Please fix the following errors:</h4>
        <ul>
          <% @restaurant.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :address, class: 'form-label' %>
      <%= form.text_field :address, class: 'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :category, class: 'form-label' %>
      <%= form.select :category, ['chinese', 'italian', 'japanese', 'french', 'belgian'], {}, class: 'form-select' %>
    </div>

    <%= form.submit 'Create Restaurant', class: 'btn btn-primary' %>
  <% end %>
  <%= link_to 'Back to List', restaurants_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1 class="mt-4 mb-4"><%= @restaurant.name %></h1>
  <p><strong>Address:</strong> <%= @restaurant.address %></p>
  <p><strong>Category:</strong> <%= @restaurant.category.capitalize %></p>
  <p><strong>Reviews</strong></p>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <p><%= review.content %> <%="⭐" * review.rating %></p>
    <% end %>
  </ul>
  <br>
  <div class="mt-4">
    <%= link_to 'Back to List', restaurants_path, class: 'btn btn-primary' %>
    <%= link_to 'Edit',  edit_restaurant_path(@restaurant), class: 'btn btn-primary' %>
  </div>
</div>
<div class="container">
  <h1>New Review for <%= @restaurant.name %></h1>

  <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating, collection: 0..5 %>
    <%= f.submit 'Submit Review', class: 'btn btn-primary' %>
  <% end %>

  <%= link_to 'Back', restaurant_path(@restaurant), class: 'btn btn-secondary' %>
</div>